### PR TITLE
Make the Waffle clickable

### PR DESCRIPTION
**Pull request by scotty3785**
Adds new functionality to the waffle to make it clickable. 
Provides a clickable waffle example.

### CODE REVIEW

**Comment by scotty3785** [comment]
Worth pointing out that at the moment when you have large padding between dots/squares, clicking in the padding to the left or above an item will register a click. Hopefully not a huge issue and it does keep the algorithm simpler.

**Comment by lawsie** [comment]
Cool, thanks. I'm sorry that I haven't had a proper chance to look/merge this yet. Lots on at the moment!

**Comment by scotty3785** [comment]
No problem. Just an FYI.

**Comment by lawsie** [comment]
@scotty3785 Please could you change the pull request to go into the branch `version-0.4`? :)

**Comment by scotty3785** [comment]
Is there an obvious way to change the branch? Does it mean raising a new pull request?

**Comment by lawsie** [comment]
I think you can just change the branch in the gui - see this page, 3rd reply:
https://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github

**Comment by scotty3785** [comment]
I've changed it to version-0.4. Hopefully this works

**Comment by lawsie** [comment]
Brill, cheers. I wanted to keep you on the log for contributions, but to put the new stuff into a different branch for testing before merging it to master!

**Comment by scotty3785** [comment]
Welcome. Let me know if there are any issues with it. Very happy to be able to put my tkinter knowledge to work.

**Pull request merged**
