### PR TITLE
Bind event handlers through friendly functions

### PR DESCRIPTION
**Pull request by drussell1974**
# Easy binding

Using tkinter binding is done by specifying the action as a string.

```
ctrl.bind("<Button-1>", mouse_button_callback)
ctrl.bind("<KeyPress>", keydown_callback)
```

The proposed change includes functions with friendly names for binding callback functions (Thin wrappers).

```
ctrl.on_mouse_press_left_button(mouse_button_callback)
ctrl.on_key_down(keydown_callback)
```

## Advantage

Use of events, allow a more interactive approach. For example, finding out which key was pressed. 

```
from guizero.guizero import *

def action(e):
    print(e.keysym)

app = App()
txt1 = TextBox(app, "")
txt1.on_key_down(action)

app.display()
```

# By convension

Using a conventions of a prefix on_, with support of intellisense in the IDE, the available "delegate" function will be shown grouped together.

image

# Learning

Handling events in separate functions, to promote decomposition.

Furthermore, passing the function, to the delegate, is synonymous with teaching students to use the onclick attribute in javascript or using delegates in C# WinForms.

**Javascript**
`<button id="txt1" onclick="myFunction()">Click me</button>`

**C# event binding**
`txt1.Click += new KeyDownEventHandler(Action_Method)`

Enum, from previous pull request, no longer exists due to compatibility with version of Python < 3.4.

### CODE REVIEW

**Comment by lawsie** [comment]
Wonderful, thanks for the extra info and explanation. Will have a proper look when I get time but thanks for taking the time to do this! :)

**Comment by drussell1974** [comment]
No problem. I was a C# developer but new to Python, so thank you for the opportunity to contribute to something that will give me hands on - and hopefully make a difference.

**Comment by lawsie** [comment]
Not ignoring this, but I ran out of time tonight and there are merge conflicts! :)

**Comment by lawsie** [comment]
I'm planning to add key bindings in next update (mostly so that you can make snake with a waffle, woo hoo!) Because I took a while to merge this there are some conflicts but I'll have a look at those when I merge. As for when, I don't know - next time I'm in a hotel and bored! :)

**Comment by martinohanlon** [comment]
Adding events to guizero is a great idea, so I have created issue #120 to keep track of this discussion.

**Comment by martinohanlon** [comment]
I am going to close this PR - this spawned some great conversations (thank) about how to manage events and an issue #120 is currently open to do this, but this PR is so behind the code base it couldn't be implemented.

**Pull request closed without merging**
