### PR TITLE
Auto update of GUI

### PR DESCRIPTION
**Pull request by ukBaz**
Add the “update” method to the App class so that a user callback will
be executed after a specified time.
Example shows how user would specify a function to read a sensor at a
specified time interval and displayed on GUI. To make the example
portable, a random number is generated rather than reading a sensor.

### CODE REVIEW

**Comment by ukBaz** [comment]
I'd be interested in peoples feedback on this.
Could it be implemented a better way?

**Comment by jezdean** [comment]
You're updating and redrawing the entire instance of App(). Wouldn't a better way to be:

```
def get_sensor_reading():
    return random.randrange(1,100)

def update_label():
    label["text"] = get_sensor_reading()
    label.after(500, update_label)

label.after(500, update_label)
```
and `.after()` is already exposed?

**Comment by ukBaz** [comment]
Thanks [Jez](@jezdean) for the feedback. Your example does seem more efficient so I've tried to update the example as you suggested. I couldn't get the `label['text']` bit to work. Did I misunderstand something?

**Comment by jezdean** [comment]
Hi Baz. Not sure why I used `Label()`... just did! In full it would be:


```
app = App()
label = Label(app, text="Waiting for Data")
label.grid(row=0)


def get_sensor_reading():
    return random.randrange(1, 100)


def update_label():
    label["text"] = get_sensor_reading()
    label.after(500, update_label)

label.after(500, update_label)

app.display()
```

**Pull request merged**
