### PR TITLE
Ask questions with simple dialog

### PR DESCRIPTION
**Pull request by scotty3785**
Tkinter has some simple dialogs that pop up to ask the user a question.
This pull request adds a very simple question dialog to guizero which will return a string to the main program. 

Rationale for change was helping at a Code Club with a simple program to ask the user for their name and I was surprised that these simple dialogs hadn't found their way in yet like the alerts have.

What do you think?

### CODE REVIEW

**Comment by scotty3785** [comment]
Usage is

`from guizero import question
....
print(question("Hello","What is your name?"))
`

**Comment by martinohanlon** [comment]
Great idea.

A few thoughts (not necessarily for you to answer...)

+ I think the `question` function should probably accept an initial value as well, but defaulted to `None` e.g.

```python
def question(title, question, initial_value=None):
```

+ I wonder whether `question` should also be available as a method of an `App` or `Window` which would allow for the `parent` to be set when calling `askstring` in tkinter e.g.

```python
app = App()
app.question("Name", "Whats your name?")
```

Note - re this I also wonder whether its worth setting up the same for the alerts so you can do `app.warning("Warn", "Be aware")`

+ I think this should go into a `dialog.py` module rather than `question.py` so it can be used for other "dialogs" in the future (file springs to mind).

+ Documentation will need to be updated, I wonder whether its worth putting this and the alerts into a new section called "pop-ups".

**Comment by scotty3785** [comment]
I like your ideas.

- questions.py to dialog.py - easily done. I like the idea of this since I also think the file save/file open dialogs would be helpful
- initial_value - again easily done. 
- app.question - Was initially unsure about how this would work but I did get it working by adding a new mixin DialogMixin and inheriting this behaviour in the BaseWindow class. I'm not sure whether this is the correct route though given my unfamiliarity with how the mixin 'structure' works. 

I'll push all these changes to my remote branch if you want to have a look at them.

**Comment by lawsie** [comment]
I have no idea why I didn't originally add this as one of the alerts! I agree that the warnings are not often used, and are in a bit of a weird place in the docs so could probably use some work.

**Comment by martinohanlon** [comment]
I am going to merge this change into a separate branch `dialog`

**Comment by scotty3785** [comment]
Ok. Let me know if you want a further pull request with your proposed changes

**Comment by martinohanlon** [comment]
Thanks, as this PR is now closed I have raised issue https://github.com/lawsie/guizero/issues/298 to track the change.

**Pull request merged**
