### PR TITLE
Update App.py

### PR DESCRIPTION
**Pull request by IDF31**
Added on_mouse_click,on_key_pressed and on_mouse_moved functions for App

### CODE REVIEW

**Comment by Coal0** [comment]
[Closely related](https://github.com/lawsie/guizero/pull/14), though it is unlikely it will be merged (conflicts).

**Comment by IDF31** [comment]
This one seems to don't have any conflicts.

**Comment by Coal0** [comment]
I was talking about the other PR. Shouldn't this be part of a MixIn, if any?

**Comment by IDF31** [comment]
Good Idea

**Comment by martinohanlon** [comment]
Thanks a lot for the PR, its great to see people get engaged with guizero.

A few things:
1. I agree with @Coal0 the implementation of this should be via a mixin (although Im not sure it should be a direct tkmixin - as the implementation may be different)
2. Should these be implemented as properties, using gpiozero as an example interface:

```
def my_func():
    print("hi")
button = Button(17)
button.when_pressed = my_func
```

If implemented as properties (which I think is a good idea) should they be `when_mouse_clicked`, `when_key_pressed`, `when_mouse_moved` - its a bit verbose, but it is simple to understand.

3. The tk callbacks will return an `Event` object [http://effbot.org/tkinterbook/tkinter-events-and-bindings.htm](http://effbot.org/tkinterbook/tkinter-events-and-bindings.htm) - is this the right thing to do for guizero? One of the problems is that the `Event` object is a tk object not a guizero object, so (as an example) it refers to the tk widget not the guizero widget.

**Comment by martinohanlon** [comment]
Adding events to guizero is a great idea, so I have created issue #120 to keep track of this discussion.

**Comment by IDF31** [comment]
Thank you! I'll follow your advice.

**Comment by IDF31** [comment]
Closing this PR because I reforked the repo

**Pull request closed without merging**
