### PR TITLE
Added event properties

### PR DESCRIPTION
**Pull request by IDF31**

### CODE REVIEW

**Comment by IDF31** [comment]
Is this going to be merged?

**Comment by martinohanlon** [comment]
Probably, I can't commit to when though, there are other things higher up the priority list at the moment.

**Comment by IDF31** [comment]
I see

**Comment by martinohanlon** [comment]
Targetting 0.5.0

**Comment by IDF31** [comment]
Thanks!

**Comment by martinohanlon** [comment]
Experimental support for events will go into v0.5.0.

The implementation was significantly more complicated than first anticipated. There are details in issue #120 

You can also see the changes I made in the `events` branch https://github.com/lawsie/guizero/tree/events

**Comment by IDF31** [comment]
Thanks man I really appreciate it :)

2018-04-08 16:50 GMT+03:00 martinohanlon <notifications@github.com>:

**Pull request closed without merging**
