### PR TITLE
Add `step` to Slider

### PR DESCRIPTION
**Pull request by james-pcdr**
Hello all,
Let me know if you have any feedback.
Thanks, and thanks for making guizero!

### CODE REVIEW

**Comment by lawsie** [comment]
Hi @james-pcdr thanks for this! It seems like a good idea to me, are you happy @martinohanlon ? Please could you add docs changes to your PR as well? (You only need to change the .md files not the HTML)

**Comment by martinohanlon** [comment]
Can we add properties to modify the step the same way that exist for start and end? That would make it consistent and allow users to change the step after the widget has been created.

**Comment by martinohanlon** [comment]
> @lawsie Sure! So those would be in [slider.md](https://github.com/lawsie/guizero/blob/master/docs-src/docs/slider.md) and [test_slider.py](https://github.com/lawsie/guizero/blob/master/tests/test_slider.py)?

Yes, that is right :)

**Comment by james-pcdr** [comment]
I started a [new PR](https://github.com/lawsie/guizero/pull/511) so that it would be a single commit based on the `dev` branch.

**Pull request closed without merging**
